server:
  port: ${GATEWAY_PORT:8080}

jwt:
  secret: ${JWT_SECRET:2LM1OEf2filBHvqs2JMdaQBj2sWCqg7g}

spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: auth-service
          uri:  ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/**

     # Ruta para el servicio de tareas (protegida)
        - id: task-service-tareas
          uri:  ${TASK_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/tareas/**
          filters:
            - name: AuthenticationFilter

        - id: patient-service-route
          uri: ${PATIENT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/patients/**
          filters:
            - name: AuthenticationFilter

  webflux:
    cors:
      filter:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5500"
              - "http://127.0.0.1:5500"
              - "https://xiomaocampo.site"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            allowedHeaders:
              - "*" # Permite todos los headers
            allowCredentials: true # Permite el envío de credenciales (cookies, headers de autorización)
            maxAge: 3600 # Cachea los resultados de la pre-verificación de CORS por 1 hora